name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Test node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: npm ci

      - name: Check lint
        run: npm run lint

      - name: Production build
        run: npm run build

      # - name: Run test
      #   run: |
      #     npm start &
      #     sleep 5 &&
      #     npm test
      #   env:
      #     WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #     MONGOOSE_AUTH: ${{ secrets.MONGOOSE_AUTH }}
      #     MONGOOSE_ID: ${{ secrets.MONGOOSE_ID }}
      #     MONGOOSE_PW: ${{ secrets.MONGOOSE_PW }}
